`Service_Participant` does not use `ConfigStore`
OpenDDS/OpenDDS pull request #4138
Opened 2023-05-09 16:05 UTC by jrw972

Problem
-------

The `Service_Participant` does not use the `ConfigStore`.  See #4134.

Solution
--------

Convert the `Service_Participant` to use the `ConfigStore`.

* Methods that returned references to configuration values in `Service_Participant` have been removed.

* Various strings have changed type.

* Each configuration value has a canonical name starting with `OPENDDS`.  The rest of the name is taken from its position in the config file by considering the section name.  Camelcase is converted into all-caps with underscores.  The canonical name resembles an environment variable to enable eventual support for environment variables.  See `Service_Participant.h` for the current list of configuration values.

* Argument parsing has been consolidated.  Arguments starting with `-DCPS`, `-Federation`, or `-OPENDDS` are canonicalized and added to the `ConfigStore`.  `-DCPS` and `-Federation` options are prefix with `OPENDDS_COMMON_`.  The ability to passes options via `-OPENDDS` means that any configuration value can be changed via the command line once all modules have adopted the `ConfigStore`.

* The configuration file is loaded into the `ConfigStore`.  The section name and key are concatenated and canonicalized.

* Configuration that involved more than setting a value has been implemented via an Internal DDS Listener.  The appropriate values are written into the `ConfigStore` and then the listener is manually invoked for the changes.  It is possible to set the listener for the reader if it is necessary to react to changes after the initial configuration.

2023-05-11 21:07 UTC, iguessthislldo commented
> * Arguments starting with `-DCPS`, `-Federation`, or `-OPENDDS` are canonicalized and added to the `ConfigStore`.  `-DCPS` and `-Federation` options are prefix with `OPENDDS_COMMON_`.

`-OPENDDS` isn't really consistent with existing arguments and capitalization and underscores should be avoided in command line arguments. I'd prefer `--opendds-`. but `-OpenDDS` would be consistent with what we already have.

2023-05-15 18:30 UTC, sonndinh commented on dds/DCPS/Service_Participant.h
> +  bool get_security();
```suggestion
  bool get_security() const;
```

2023-05-15 18:30 UTC, sonndinh commented on dds/DCPS/Service_Participant.h
> +  bool get_BIT();
```suggestion
  bool get_BIT() const;
```

2023-05-17 17:41 UTC, iguessthislldo requested changes

2023-05-17 17:41 UTC, iguessthislldo commented on dds/DCPS/Service_Participant.h
> +const char OPENDDS_COMMON_DCPS_CHUNK_ASSOCIATION_MUTLTIPLIER[] = "OPENDDS_COMMON_DCPS_CHUNK_ASSOCIATION_MUTLTIPLIER";
Yes, I think so, as we don't know who's using it.

2023-05-18 20:16 UTC, iguessthislldo requested changes

2023-05-18 20:16 UTC, iguessthislldo commented on dds/DCPS/Service_Participant.cpp
> +  config_store_.set_uint32(OPENDDS_COMMON_DCPS_CHUNKS, chunks);
Narrowing warnings here and below

2023-05-18 20:16 UTC, iguessthislldo commented on dds/DCPS/Service_Participant.h
> +#endif
The preprocessor and C++ indents should probably be independent of each other.

2023-05-19 21:53 UTC, merged