Create SECURITY.md
OpenDDS/OpenDDS pull request #4303
Opened 2023-10-12 21:38 UTC by jrw972

2023-10-12 23:27 UTC, iguessthislldo requested changes
Is there anywhere else that should mention this (devguide, website, etc.) or is this mostly a GitHub thing?

2023-10-12 23:27 UTC, iguessthislldo commented on SECURITY.md
> +  If the vulnerability is intrinsic to the DDS/RTPS Specification and using DDS Security would address it, then the maintainers of OpenDDS will most likely not accept the vulnerability report and sug
```suggestion
  If the vulnerability is intrinsic to the DDS/RTPS Specification and using DDS Security would address it, then the maintainers of OpenDDS will most likely not accept the vulnerability report and suggest using DDS Security.
```

2023-10-13 14:11 UTC, jrw972 commented
> Is there anywhere else that should mention this (devguide, website, etc.) or is this mostly a GitHub thing?

I don't think so.  I think GitHub is exploiting/creating a convention.

2023-10-13 14:33 UTC, iguessthislldo approved these changes

2023-10-13 16:37 UTC, sonndinh approved these changes

2023-10-16 18:07 UTC, merged