Fixes and Tweaks for CMake Documentation
OpenDDS/OpenDDS pull request #4314
Opened 2023-10-17 19:48 UTC by iguessthislldo

2023-10-17 20:03 UTC, mitza-oci requested changes

2023-10-17 20:03 UTC, mitza-oci commented on docs/devguide/building/cmake.rst
> +They can be changed when configuring a :ref:`CMake-built OpenDDS <cmake-building>` using ``-D``, but should not be chagned after that.
```suggestion
These variables are set by the ``configure`` script in an MPC-built OpenDDS and normally shouldn't be changed.
They can be changed when configuring a :ref:`CMake-built OpenDDS <cmake-building>` using ``-D``, but should not be changed after that.
```

2023-10-17 21:25 UTC, mitza-oci approved these changes

2023-10-17 22:56 UTC, mitza-oci approved these changes

2023-10-18 13:53 UTC, jrw972 approved these changes

2023-10-18 18:03 UTC, jrw972 approved these changes

2023-10-18 22:06 UTC, merged