Sync 3.26.1 News and Release Script Updates
OpenDDS/OpenDDS pull request #4356
Opened 2023-11-17 00:47 UTC by iguessthislldo

Added a small utility to cherry pick GitHub PRs to help prepare micro releases and fixed updating links in README for micro releases.

2023-11-17 07:21 UTC, jwillemsen commented
To backport PRs I have tried https://mergify.com, also works useful, you can already tag the PR before it is merged, when the PR is merged the backport PR is automatically created

2023-11-17 15:05 UTC, jrw972 requested changes

2023-11-17 15:05 UTC, jrw972 commented on NEWS.md
> +Read [the documenation for this release on Read the Docs](https://opendds.readthedocs.io/en/dds-3.26.1).
```suggestion
Read [the documentation for this release on Read the Docs](https://opendds.readthedocs.io/en/dds-3.26.1).
```

2023-11-17 15:05 UTC, jrw972 commented on docs/news.d/_releases/v3.26.1.rst
> +Read `the documenation for this release on Read the Docs <https://opendds.readthedocs.io/en/dds-3.26.1>`__.
```suggestion
Read `the documentation for this release on Read the Docs <https://opendds.readthedocs.io/en/dds-3.26.1>`__.
```

2023-11-20 16:25 UTC, jrw972 approved these changes

2023-11-20 19:03 UTC, merged