`create_datawriter/datareader` do not check topic participant
OpenDDS/OpenDDS pull request #4398
Opened 2023-12-18 20:33 UTC by jrw972

Problem
-------

Sections 2.2.2.4.1.5 and 2.2.2.5.2.5 of the DDS Specification say that `create_datawriter` and `create_datareader` should fail if the topic does not belong to the same participant as the publisher/subscriber.

Solution
--------

Add the necessary checks to `create_datawriter` and `create_datareader`.

2023-12-18 21:02 UTC, mitza-oci approved these changes

2023-12-18 22:55 UTC, iguessthislldo requested changes

2023-12-18 22:55 UTC, iguessthislldo commented on docs/news.d/create-writer-reader-topic.rst
> +- `create_datawriter` and `create_datareader` check if the topic belongs to the same participant as the publisher/subscriber.
```suggestion
- ``create_datawriter`` and ``create_datareader`` check if the topic belongs to the same participant as the publisher/subscriber.
```

2023-12-19 00:11 UTC, sonndinh approved these changes

2023-12-19 18:50 UTC, iguessthislldo approved these changes

2023-12-19 19:04 UTC, merged