`load_discovery_template` does not use ConfigStore
OpenDDS/OpenDDS pull request #4409
Opened 2024-01-03 15:16 UTC by jrw972

Problem
-------

`load_discovery_template` does not use ConfigStore.  See #4134.

Solution
--------

Convert `load_discovery_template` to use ConfigStore.

2024-01-03 23:17 UTC, mitza-oci requested changes

2024-01-03 23:17 UTC, mitza-oci commented on dds/DCPS/transport/framework/TransportRegistry.h
> +  int load_transport_templates();
Update the doxygen comment above this

2024-01-04 16:49 UTC, sonndinh commented on dds/DCPS/transport/framework/TransportRegistry.cpp
> +      const bool is_template = ACE_OS::strcmp(sect_name.c_str(), TRANSPORT_TEMPLATE_SECTION_NAME) == 0;
The same `strcmp` call is performed twice. Can `is_template` be created before the `if` block?

2024-01-04 19:03 UTC, mitza-oci approved these changes

2024-01-05 19:02 UTC, merged