`[domain/*]` does not use `ConfigStore`
OpenDDS/OpenDDS pull request #4454
Opened 2024-01-31 18:57 UTC by jrw972

Problem
-------

`[domain/*]` does not use ConfigStore. See #4134.

Solution
--------

Convert `[domain/*]` to use ConfigStore.

2024-02-05 20:34 UTC, iguessthislldo requested changes

2024-02-05 20:34 UTC, iguessthislldo commented on dds/DCPS/Service_Participant.cpp
> -  if (cf.open_section(root, DOMAIN_SECTION_NAME, false, domain_sect) != 0) {
`DOMAIN_SECTION_NAME` has unused warnings on them.

2024-02-05 23:06 UTC, iguessthislldo approved these changes

2024-02-06 18:44 UTC, sonndinh commented on dds/DCPS/Service_Participant.cpp
> +                 domain.name().c_str()));
```suggestion
      ACE_ERROR((LM_ERROR,
                 "(%P|%t) ERROR: Service_Participant::process_domain: "
                 "Missing DomainId value in [domain/%C] section.\n",
                 domain.name().c_str()));
```
Some other logs also miss this part.

2024-02-08 21:21 UTC, merged