Add a configurable "user tag" to SPDP
OpenDDS/OpenDDS pull request #4533
Opened 2024-03-21 21:58 UTC by mitza-oci

If the configuration specifies a non-zero tag, then that 32-bit value is added to the start of the SPDP participant announcement messages after the RTPS Header and its own Submessage Header.

Note: target branch needs to be changed before we can merge

2024-03-22 21:14 UTC, iguessthislldo requested changes

2024-03-22 21:14 UTC, iguessthislldo commented on dds/DCPS/RTPS/Spdp.cpp
>      if (DCPS::DCPS_debug_level > 0) {
```suggestion
    if (log_level >= LogLevel::Error) {
```

2024-03-22 21:14 UTC, iguessthislldo commented on dds/DCPS/RTPS/Spdp.cpp
> +    if (DCPS::DCPS_debug_level > 0) {
```suggestion
    if (log_level >= LogLevel::Error) {
```

2024-03-22 21:14 UTC, iguessthislldo commented on dds/DCPS/RTPS/Spdp.cpp
> +    if (DCPS::DCPS_debug_level > 0) {
```suggestion
    if (log_level >= LogLevel::Error) {
```

2024-03-25 15:59 UTC, jrw972 approved these changes

2024-03-25 17:29 UTC, iguessthislldo approved these changes

2024-03-25 21:45 UTC, mitza-oci commented on docs/devguide/run_time_configuration.rst
> +       Otherwise this submessage's contents is the 4-byte integer i.
I was intending it to be more general about "an integer" than the C++ data type, but maybe it's better to be specific.

2024-03-26 18:08 UTC, merged