CLOCK_BOOTTIME timers (Linux only)
OpenDDS/OpenDDS pull request #4568
Opened 2024-04-09 17:54 UTC by mitza-oci

Allow configuration of timers that use the CLOCK_BOOTTIME clock offered by Linux.

2024-04-09 19:57 UTC, jrw972 approved these changes

2024-04-10 20:53 UTC, jrw972 approved these changes

2024-04-10 23:35 UTC, iguessthislldo commented on configure
> +    'boottime|boottime!', 'Use CLOCK_BOOTTIME for timers (no)',
Does this need to be `boottime|boottime`?

2024-04-10 23:45 UTC, iguessthislldo requested changes

2024-04-10 23:45 UTC, iguessthislldo commented on dds/DCPS/PeriodicTask.cpp
> +                  " failed to schedule timer %p\n", ACE_TEXT("")));
Since we're chancing these, we should convert these to use `LogLevel::Error`, there are a few more in `Multitask.cpp`.

2024-04-10 23:45 UTC, iguessthislldo commented on configure
> +    'boottime|boottime!', 'Use CLOCK_BOOTTIME for timers (no)',
As opposed to just `boottime!`.

2024-04-11 16:24 UTC, iguessthislldo approved these changes

2024-04-11 17:35 UTC, sonndinh commented on dds/DCPS/Timers.cpp
> +
```suggestion
```

2024-04-11 18:06 UTC, merged