Debugging output not available for Messenger test
OpenDDS/OpenDDS pull request #4634
Opened 2024-05-15 14:40 UTC by jrw972

Problem
-------

Debugging is not turned on for the Messenger test.

Solution
--------

Turn on debugging.

2024-05-15 14:40 UTC, jrw972 commented
The ancillary goal is to debug some failures on different PRs.

2024-05-15 16:34 UTC, iguessthislldo requested changes
I don't think this is necessary. I think we already discussed this. The better solution would be changing [this value](https://github.com/OpenDDS/OpenDDS/blob/81660e1d67b2230b029c0cbe2430ab4317129ea2/bin/PerlDDS/Run_Test.pm#L598) back to 1 so all tests work as expected.

2024-05-15 18:11 UTC, mitza-oci commented
Related change is https://github.com/OpenDDS/OpenDDS/commit/2605ead31cb4334c388f305e0fee89aa838bf857

2024-05-16 16:44 UTC, iguessthislldo approved these changes

2024-05-16 18:10 UTC, merged