Add missing news
OpenDDS/OpenDDS pull request #4697
Opened 2024-06-14 16:32 UTC by jrw972

2024-06-14 17:00 UTC, iguessthislldo requested changes

2024-06-14 17:00 UTC, iguessthislldo commented on docs/news.d/OpenDDSConfigWrapper.rst
> +.. news-start-section: Additionos
```suggestion
.. news-start-section: Additions
```

2024-06-14 18:03 UTC, iguessthislldo requested changes

2024-06-14 18:03 UTC, iguessthislldo commented on docs/news.d/OpenDDSConfigWrapper.rst
> +  - These files should be include in preference to ``dds/OpenDDSConfig.h``
```suggestion
  - These files should be included in preference to ``dds/OpenDDSConfig.h``
```

2024-06-14 18:33 UTC, iguessthislldo approved these changes

2024-06-17 17:24 UTC, mitza-oci requested changes

2024-06-17 17:24 UTC, mitza-oci commented on docs/news.d/OpenDDSConfig.rst
> +  - Users manually configuring a build will need to create this file, which may be empty.
```suggestion
  - Users manually configuring a build will need to create dds/OpenDDSConfig.h file, which may be empty.
```

2024-06-18 14:15 UTC, mitza-oci approved these changes

2024-06-18 18:35 UTC, merged