Updated documentation
OpenDDS/OpenDDS pull request #4705
Opened 2024-06-19 21:59 UTC by mitza-oci

Mostly related to RtpsRelay
Also updated copyright year
Top-level index page: use same format for link to devguide index as other links

2024-06-19 22:04 UTC, iguessthislldo requested changes

2024-06-19 22:04 UTC, iguessthislldo commented on docs/devguide/internet_enabled_rtps.rst
> +To support this usage, the RtpsRelay includes :ref:`_internet_enabled_rtps--metadisc-server` which can be configured to serve the public IP address of the relay.
```suggestion
To support this usage, the RtpsRelay includes a :ref:`web server <internet_enabled_rtps--metadisc-server>` which can be configured to serve the public IP address of the relay.
```

2024-06-19 22:16 UTC, iguessthislldo approved these changes

2024-06-20 18:34 UTC, jrw972 approved these changes

2024-06-20 18:35 UTC, merged