`EncapsulationHeader::to_encoding_i` error messages lack detail
OpenDDS/OpenDDS pull request #4707
Opened 2024-06-21 22:16 UTC by jrw972

Problem
-------

The error messages from `EncapsulationHeader::to_encoding_i` lack enough detail to actually debug the error.  Typically, the issue is a mismatch in encoding, however, it is unclear which topic, writer, reader, etc. is involved.

Solution
--------

Add the writer and reader guids to the error messages.

2024-06-24 17:20 UTC, mitza-oci requested changes
Instead of moving additional details into the EncapsulationHeader I think we should move to_encoding out to another class or function, maybe in XTypes dir/namespace.

2024-06-24 17:49 UTC, iguessthislldo commented
I'm not sure sure about that. `EncapsulationHeader`, like `Encoding` and `Serializer` is aware of XTypes, but isn't specific to XTypes.

2024-06-24 17:52 UTC, mitza-oci commented
> I'm not sure sure about that. `EncapsulationHeader`, like `Encoding` and `Serializer` is aware of XTypes, but isn't specific to XTypes.

I was referring to moving the `to_encoding` algorithm, not the `EncapsulationHeader`.  It doesn't have to move to XTypes, but it also doesn't have to be in `Serializer.h`.

2024-06-26 16:27 UTC, iguessthislldo approved these changes

2024-06-26 17:38 UTC, mitza-oci requested changes

2024-06-26 17:38 UTC, mitza-oci commented on dds/DCPS/RTPS/Spdp.cpp
> +          if (!(ser >> encap) || !to_encoding(enc, encap, DCPS::MUTABLE)  || enc.kind() != Encoding::KIND_XCDR1) {
```suggestion
          if (!(ser >> encap) || !to_encoding(enc, encap, DCPS::MUTABLE) || enc.kind() != Encoding::KIND_XCDR1) {
```

2024-06-27 19:00 UTC, mitza-oci approved these changes

2024-06-27 22:03 UTC, iguessthislldo approved these changes

2024-06-28 20:42 UTC, merged