[fix] RtpsDiscoveryConfig RESEND_PERIOD
OpenDDS/OpenDDS pull request #4712
Opened 2024-06-27 13:52 UTC by jmmorato

Use milliseconds in order to don't lose the microseconds in the TimeDuration

2024-06-27 14:50 UTC, iguessthislldo requested changes

2024-06-27 14:50 UTC, iguessthislldo commented on dds/DCPS/RTPS/RtpsDiscoveryConfig.cpp
> +                                                    DCPS::ConfigStoreImpl::Format_IntegerMilliseconds);
`Format_FractionalSeconds`? I think `Format_IntegerMilliseconds` would make all existing usage of `ResendPeriod` much much shorter.

2024-06-27 17:16 UTC, iguessthislldo requested changes
Alright, the only things I think are left are that the documentation and news should be updated. For documentation, the only other property that's using fractional seconds is `AuthResendPeriod`:

https://github.com/OpenDDS/OpenDDS/blob/e0cd8c8bdeceef9c67bf70e38395f88fd84c1938/docs/devguide/run_time_configuration.rst?plain=1#L1381-L1385

It says it's a floating point value, so we should copy that line to `ResendPeriod`'s description:

https://github.com/OpenDDS/OpenDDS/blob/e0cd8c8bdeceef9c67bf70e38395f88fd84c1938/docs/devguide/run_time_configuration.rst?plain=1#L1106-L1109

Then for the news, I don't know if remember if you've made a PR since we added systems for the new and config properties, so I'll give it to you. Create a rst file in https://github.com/OpenDDS/OpenDDS/blob/master/docs/news.d along the lines of:

```rst
.. news-prs: 4712

.. news-start-section: Additions
- :prop:`[rtps_discovery]ResendPeriod` now accepts fractions of a second.
.. news-end-section

2024-06-27 17:22 UTC, jrw972 approved these changes

2024-06-28 17:06 UTC, iguessthislldo approved these changes

2024-06-28 18:38 UTC, merged