Union topics are not supported in Java
OpenDDS/OpenDDS pull request #4771
Opened 2024-08-15 20:12 UTC by jrw972

Problem
-------

Union topics do not compile with Java.

Solution
--------

Add support and a extend a test for union topics in Java.

2024-08-15 23:11 UTC, mitza-oci commented on dds/idl/ts_generator.cpp
> +  /// called directly by dds_visitor::visit_structure() if -Wb,java
```suggestion
  /// called directly by dds_visitor::visit_union() if -Wb,java
```

2024-08-15 23:12 UTC, mitza-oci commented on dds/idl/ts_generator.cpp
> +  /// called directly by dds_visitor::visit_structure() if -Wb,java
Also I suppose the `directly` in this comment and the one above no longer apply

2024-08-19 18:13 UTC, mitza-oci approved these changes

2024-08-19 21:25 UTC, iguessthislldo requested changes

2024-08-19 21:25 UTC, iguessthislldo commented on dds/idl/marshal_generator.cpp
> +    }
This looks like should be handled by `type_to_default`.

2024-08-21 16:50 UTC, iguessthislldo commented on dds/idl/marshal_generator.cpp
> +      string() +
`field_type_name` returns a `std::string`, so is this needed?

2024-08-22 19:08 UTC, iguessthislldo approved these changes

2024-08-22 19:09 UTC, merged