RtpsRelay cleanup
OpenDDS/OpenDDS pull request #4802
Opened 2024-09-19 20:18 UTC by mitza-oci

* Removed unused code and macros
* Moved some large inline functions to cpp files
* Used C++11 features for clarity

2024-09-19 21:18 UTC, iguessthislldo requested changes

2024-09-19 21:18 UTC, iguessthislldo commented on tools/rtpsrelay/GuidPartitionTable.cpp
> +  const auto prefix = make_id(from, OpenDDS::DCPS::ENTITYID_UNKNOWN);
```suggestion
  const auto prefix = make_unknown_guid(from);
```

2024-09-19 21:18 UTC, iguessthislldo commented on tools/rtpsrelay/GuidPartitionTable.cpp
> +  const auto prefix = make_id(guid, OpenDDS::DCPS::ENTITYID_UNKNOWN);
```suggestion
  const auto prefix = make_unknown_id(guid);
```

2024-09-19 21:18 UTC, iguessthislldo commented on tools/rtpsrelay/GuidPartitionTable.cpp
> +        std::memcmp(pos2->guidPrefix, prefix.guidPrefix, sizeof(prefix.guidPrefix)) != 0) {
```suggestion
    if (pos2 == pos1->second.end() || equal_guid_prefixes(*pos2, prefix)) {
```

2024-09-19 21:18 UTC, iguessthislldo commented on tools/rtpsrelay/GuidAddrSet.cpp
> +  std::map<u_short, OpenDDS::DCPS::MonotonicTimePoint>* port_map = nullptr;
Maybe make a `typedef`/`using` of this type to share with `PortSet`? Could also make the switch statement a method in `PortSet`.

2024-09-19 21:18 UTC, iguessthislldo commented on tools/rtpsrelay/README.rst
> +see docs/devguide/internet_enabled_rtps.rst
```suggestion
Note: More up-to-date information about the RtpsRelay is in the OpenDDS Developer's Guide
see ``docs/devguide/internet_enabled_rtps.rst``
```

2024-09-19 21:56 UTC, jrw972 approved these changes

2024-09-20 15:19 UTC, sonndinh commented on tools/rtpsrelay/GuidPartitionTable.cpp
> +        ACE_ERROR((LM_ERROR, "(%P|%t) ERROR: failed to write Relay Partitions\n"));
```suggestion
        ACE_ERROR((LM_ERROR, "(%P|%t) ERROR: GuidPartitionTable::insert failed to write Relay Partitions\n"));
```

2024-09-20 15:48 UTC, iguessthislldo approved these changes

2024-09-23 17:33 UTC, merged