[Bench] Replace worker Proactor use with EventDispatcher
OpenDDS/OpenDDS pull request #4812
Opened 2024-10-01 10:00 UTC by simpsont-oci

Problem:
Now that OpenDDS has EventDispatcher, Bench's explicit use of ACE's Proactor and thread pool management is more complexity than is strictly necessary and seems to have the potential for occasional TSAN complaints (see: https://github.com/OpenDDS/OpenDDS/actions/runs/11108130996/job/30864879221)

Solution:
Update Bench's worker process to use EventDispatcher for scheduling action tasks.

2024-10-03 15:30 UTC, sonndinh commented on performance-tests/bench/worker/ForwardAction.cpp
> +  event_ = OpenDDS::DCPS::make_rch<MemFunEvent<ForwardAction> >(shared_from_this(), &ForwardAction::do_writes);
```suggestion
  event_ = OpenDDS::DCPS::make_rch<MemFunEvent<ForwardAction>>(shared_from_this(), &ForwardAction::do_writes);
```
Don't need space with C++11?

2024-10-03 18:28 UTC, iguessthislldo requested changes

2024-10-03 18:28 UTC, iguessthislldo commented on performance-tests/bench/worker/MemFunEvent.h
> +#include "dds/DCPS/EventDispatcher.h"
```suggestion
#include <dds/DCPS/EventDispatcher.h>
```

2024-10-03 18:28 UTC, iguessthislldo commented on performance-tests/bench/worker/ReadAction.h
> +#include "dds/DCPS/EventDispatcher.h"
```
#include <dds/DCPS/GuardCondition.h>
#include <dds/DCPS/EventDispatcher.h>
```

2024-10-03 18:28 UTC, iguessthislldo commented on performance-tests/bench/worker/WriteAction.cpp
>        }
```suggestion
      if (relative_scheduling_) {
        last_scheduled_time_ = OpenDDS::DCPS::MonotonicTimePoint::now();
      }
      last_scheduled_time_ += OpenDDS::DCPS::TimeDuration(write_period_);
```

2024-10-03 18:28 UTC, iguessthislldo commented on performance-tests/bench/worker/SetCftParametersAction.cpp
> +    last_scheduled_time_ += OpenDDS::DCPS::TimeDuration(set_period_);
Maybe turn these member `ACE_Time_Value`s into `TimeDuration`s since they're not being passed directly to ACE anymore?

2024-10-04 15:59 UTC, sonndinh approved these changes

2024-10-07 14:43 UTC, iguessthislldo approved these changes

2024-10-07 17:32 UTC, merged