DevGuide lacks cmake example for MacOS that works by default
OpenDDS/OpenDDS pull request #4831
Opened 2024-10-25 19:29 UTC by jrw972

Problem
-------

The cmake example for MacOS doesn't work by default.

Solution
--------

Add an example that works.

2024-10-25 19:30 UTC, mitza-oci approved these changes

2024-10-27 17:09 UTC, iguessthislldo requested changes
This sounds like something is wrong with CMake standard stuff. You shouldn't have to specify the standard.

2024-10-27 17:11 UTC, iguessthislldo commented
> The cmake example for MacOS doesn't work by default.

How exactly?

2024-10-28 16:34 UTC, jrw972 commented
> > The cmake example for MacOS doesn't work by default.
> 
> How exactly?

I think I wrote this and stashed it before the cmake support handled the C++ versions the way it does now.
At that point, cmake would use ACE 7 which needed at least C++11 but the system default was 98 so things would not compile.

2024-10-28 16:34 UTC, closed without merging